Enable choosing source repo

diff --git a/add-issues-to-project/action.yml b/add-issues-to-project/action.yml
--- a/add-issues-to-project/action.yml
+++ b/add-issues-to-project/action.yml
@@ -1,15 +1,24 @@
 name: "Add Issues to Project"
-description: "Adds issues from the repository to a specified GitHub Project."
-author: "SATVILab"
+description: "Adds issues from a specified repository to a specified GitHub Project."
+author: "MiguelRodo"
+
 inputs:
   project_name:
-    description: "Name of the project to which issues should be added"
-    required: true
-    default: ""
-  org_name:
-    description: "Name of the organization (if the project is an organization project)"
+    description: "Project name. Defaults to repository name."
     required: false
-    default: "SATVILab"
+  project_owner:
+    description: "Project owner. Defaults to repository owner."
+    required: false
+  is_project_owner_org:
+    description: "Whether the project owner is an organization. Defaults to `false`."
+    required: false
+    default: "false"
+  source_repo_name:
+    description: "Repository name. Defaults to current repository."
+    required: false
+  source_repo_owner:
+    description: "Repository owner. Defaults to current GitHub user."
+    required: false
   ADD_ISSUES_TO_PROJECT_TOKEN:
     description: "GitHub token with correct access for accessing issues and writing to projects"
     required: true
@@ -18,56 +27,170 @@ runs:
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+
     - name: Set up GitHub CLI and jq
       shell: bash
       run: |
         sudo apt update -y
         sudo apt install -y gh jq
+
+        echo "GitHub CLI version: $(gh --version)"
+        echo "jq version: $(jq --version)"
+
     - name: Authenticate with PAT
       shell: bash
       env:
-        ADD_ISSUES_TO_PROJECT_TOKEN: "${{ env.ADD_ISSUES_TO_PROJECT_TOKEN }}"
+        PROJECT_TOKEN: "${{ inputs.ADD_ISSUES_TO_PROJECT_TOKEN  }}"
       run: |
-        unset GH_TOKEN
         unset GITHUB_TOKEN
-        echo "$ADD_ISSUES_TO_PROJECT_TOKEN" | gh auth login --with-token
+        unset GH_TOKEN
+        if [ -z "$PROJECT_TOKEN" ]; then
+          echo "Error: No token provided."
+          exit 1
+        fi
+        echo "$PROJECT_TOKEN" | gh auth login -h github.com --with-token
+        echo "gh auth status:"
+        gh auth status
+        echo "gh token list:"
+        gh auth token
+
     - name: Install gh-projects extension
       shell: bash
       run: gh extension install github/gh-projects
+
+    - name: Validate input and format used values
+      shell: bash
+      env:
+        PROJECT_NAME: "${{ inputs.project_name }}"
+        PROJECT_OWNER: "${{ inputs.project_owner }}"
+        IS_PROJECT_OWNER_ORG: "${{ inputs.is_project_owner_org }}"
+        SOURCE_REPO_NAME: "${{ inputs.source_repo_name }}"
+        SOURCE_REPO_OWNER: "${{ inputs.source_repo_owner }}"
+        CURRENT_USER: "${{ github.actor }}"
+      run: |
+        if [ -z "${SOURCE_REPO_NAME}" ]; then
+          SOURCE_REPO_NAME=$(basename "$(pwd)")
+        fi
+        if [ -z "${PROJECT_NAME}" ]; then
+          PROJECT_NAME_FINAL="$SOURCE_REPO_NAME"
+        else
+          PROJECT_NAME_FINAL="$PROJECT_NAME"
+        fi
+        if [ -z "${SOURCE_REPO_OWNER}" ]; then
+          SOURCE_REPO_OWNER="$CURRENT_USER"
+        fi
+        if [ -z "${PROJECT_OWNER}" ]; then
+          PROJECT_OWNER_FINAL="$SOURCE_REPO_OWNER"
+        else
+          PROJECT_OWNER_FINAL="$PROJECT_OWNER"
+        fi
+        SOURCE_REPO="${SOURCE_REPO_OWNER}/${SOURCE_REPO_NAME}"
+
+        echo "Project name: $PROJECT_NAME_FINAL"
+        echo "Project owner: $PROJECT_OWNER_FINAL"
+        echo "Source repository: $SOURCE_REPO"
+
+        # validate source repo format
+        if [[ ! "$SOURCE_REPO" =~ ^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$ ]]; then
+          echo "Error: Invalid source repository format. Expected format: owner/repo."
+          exit 1
+        else
+          echo "Source repository format is valid."
+        fi
+
+        # check that owners exist
+        if [ "${IS_PROJECT_OWNER_ORG}" = "true" ]; then
+          gh api orgs/"${PROJECT_OWNER_FINAL}" > /dev/null
+          if [ $? -ne 0 ]; then
+            echo "Error: Organization '${PROJECT_OWNER_FINAL}' not found."
+            exit 1
+          else 
+            echo "Organization '${PROJECT_OWNER_FINAL}' found."
+          fi
+        else
+          gh api users/"${PROJECT_OWNER_FINAL}" > /dev/null
+          if [ $? -ne 0 ]; then
+            echo "Error: User '${PROJECT_OWNER_FINAL}' not found."
+            exit 1
+          else
+            echo "User '${PROJECT_OWNER_FINAL}' found."
+          fi
+        fi
+
+        # check that repo exists
+        gh api repos/"${SOURCE_REPO}" > /dev/null
+        if [ $? -ne 0 ]; then
+          echo "Error: Repository '${SOURCE_REPO}' not found."
+          exit 1
+        fi
+
+        echo "project_name=${PROJECT_NAME_FINAL}" >> $GITHUB_ENV
+        echo "project_owner=${PROJECT_OWNER_FINAL}" >> $GITHUB_ENV
+        echo "source_repo=${SOURCE_REPO}" >> $GITHUB_ENV
+
+        echo "Completed input validation."
+
     - name: Get project ID
       id: get-project-id
       shell: bash
       env:
-        PROJECT_NAME: "${{ inputs.project_name }}"
-        ORG_NAME: "${{ inputs.org_name }}"
+        PROJECT_NAME: "${{ env.project_name }}"
+        PROJECT_OWNER: "${{ env.project_owner }}"
+        IS_PROJECT_OWNER_ORG: "${{ inputs.is_project_owner_org }}"
       run: |
-        if [ -z "${ORG_NAME}" ]; then
-          project_number=$(gh projects list --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .number')
-          project_id=$(gh projects list --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+        echo "Getting project ID for project '${PROJECT_NAME}' owned by '${PROJECT_OWNER}'..."
+        if [ "${IS_PROJECT_OWNER_ORG}" = "true" ]; then
+          echo "Treating project owner as an organization."
+          project_list=$(gh projects list --org "${PROJECT_OWNER}" --format json) || {
+            echo "Error: Could not obtain project list."
+            exit 1
+          }
         else
-          project_number=$(gh projects list --org "${ORG_NAME}" --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .number')
-          project_id=$(gh projects list --org "${ORG_NAME}" --format json | jq '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id')
+          echo "Treating project owner as a user."
+          project_list=$(gh projects list --user "${PROJECT_OWNER}" --format json) || {
+            echo "Error: Could not obtain project list."
+            exit 1
+          }
         fi
 
-        if [ -z "${project_number}" ] || [ -z "${project_id}" ]; then
-          echo "Error: Project '${PROJECT_NAME}' not found."
+        # Display the project list for debugging purposes
+        echo "project_list: $project_list"
+
+        # Attempt to extract the project ID
+        project_id=$(echo "$project_list" | jq -r '.projects[] | select(.title=="'"${PROJECT_NAME}"'") | .id') || {
+          echo "Error: Could not extract project ID."
           exit 1
+        }
+
+        if [ -z "$project_id" ]; then
+          echo "Error: Project ID not found for project '${PROJECT_NAME}' owned by '${PROJECT_OWNER}'."
+          exit 1
+        else
+          echo "Project ID found: ${project_id}"
         fi
 
-        echo "project_number=${project_number}" >> $GITHUB_ENV
+        # Export project ID to the GitHub environment
         echo "project_id=${project_id}" >> $GITHUB_ENV
-    - name: Get issues from repository
+
+    - name: Get issues from source repository
       id: get-issues
       shell: bash
+      env:
+        SOURCE_REPO: "${{ env.source_repo }}"
       run: |
-        issues=$(gh issue list --repo "${{ github.repository }}" --limit 9999 --json number --jq '.[].number' | tr '\n' ' ')
+        issues=$(gh issue list --repo "${SOURCE_REPO}" --limit 9999 --json number --jq '.[].number' | tr '\n' ' ')
+        if [ -z "$issues" ]; then
+          echo "No issues found in repository '${SOURCE_REPO}'."
+          exit 0
+        fi
         echo "issues=$issues" >> $GITHUB_ENV
+
     - name: Add issues to project if not already present
       shell: bash
       env:
         ISSUES: "${{ env.issues }}"
-        ADD_ISSUES_TO_PROJECT_TOKEN: "${{ env.ADD_ISSUES_TO_PROJECT_TOKEN }}"
         PROJECT_ID: "${{ env.project_id }}"
+        SOURCE_REPO: "${{ env.source_repo }}"
       run: |
         existing_issue_ids=()
         has_next_page=true
@@ -85,7 +208,7 @@ runs:
 
         existing_issue_ids_str="${existing_issue_ids[*]}"
         for issue in $ISSUES; do
-          issue_node_id=$(gh issue view $issue --repo "${{ github.repository }}" --json id --jq '.id')
+          issue_node_id=$(gh issue view "$issue" --repo "${SOURCE_REPO}" --json id --jq '.id')
           if [[ " ${existing_issue_ids_str[@]} " =~ " $issue_node_id " ]]; then
             echo "Issue #$issue is already in the project. Skipping."
           else
